version: 2

updates:
  - package-ecosystem: "uv"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 1
    allow:
      - dependency-type: "direct"
        update-types:
          - "version-update:semver-minor"
    commit-message:
      prefix: "deps"
    labels:
      - "backend"
      - "dependencies"
    groups:
      uv-all-updates:
        applies-to: "version-updates"
        update-types:
          - "minor"
        patterns:
          - "*"
